### ISSUE TITLE
Maintain repository

### ISSUE THREAD

**Issue by elizeuangelo** [jessev14/ambient-soundbits#2]
Hey there!

I updated this module to v10 and added some new funcionalities, and I was wondering if I either:
- I should make a pull request or
- Maybe you should point the manifest to my page?

Im wondering this because the last update was almost a year ago.

The link to my fork:
https://github.com/elizeuangelo/fvtt-module-ambient-soundbits

**Comment by jessev14** [comment]
I appreciate the work. You can make a PR and I'll merge and update the package page.

**Comment by elizeuangelo** [comment]
Done! #3
